name: Build Docker Image

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

env:
  DOCKER_IMAGE: "gcr.io/platform-235214/ratehub-express-gateway"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Get tag from ref
        id: set-tag
        run: |
          echo "::set-output name=docker_tag::${GITHUB_REF_NAME}"
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCP_SA_KEY_JSON }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:${{ steps.set-tag.outputs.docker_tag }},${{ env.DOCKER_IMAGE }}:latest